import re
from pathlib import Path

f = Path('/home/faqih/projects/restaurant-demo/evidence_en/pages/02-branch-performance/deepdive.md')
c = f.read_text()

# Variables Translation
c = c.replace("'Bulan Ini (MTD)'", "'This Month (MTD)'")
c = c.replace("'semua biaya dalam batas'", "'all costs within limits'")
c = c.replace("'biaya operasional'", "'operational costs'")
c = c.replace("'biaya bahan'", "'Ingredient Costs'")
c = c.replace("'biaya SDM'", "'Labor Costs'")
c = c.replace("'hari serupa (SDOW) minggu lalu'", "'similar day (SDOW) last week'")
c = c.replace("'7 hari sebelumnya'", "'previous 7 days'")
c = c.replace("'30 hari sebelumnya'", "'previous 30 days'")
c = c.replace("'menu andalan'", "'flagship menu'")
c = c.replace("'pencetak omzet'", "'revenue generator'")

# Executive Summary HTML fixes
c = c.replace("KESIMPULAN EKSEKUTIF:", "EXECUTIVE SUMMARY:")
c = c.replace("'Performance Location Prima'", "'Prime Location Performance'")
c = c.replace("'Location Butuh Perhatian'", "'Location Needs Attention'")
c = c.replace("'Crisis Profitabilitas'", "'Profitability Crisis'")
c = c.replace("<strong>namun</strong>", "<strong>however</strong>")
c = c.replace("volume bisnis sedang mengalami kontraksi", "business volume is experiencing contraction")

# Other leftover string tags
c = c.replace("<strong>Pangkas Shift.</strong>", "<strong>Cut Shifts.</strong>")
c = c.replace("Kurangi shift karyawan <em>part-time</em> di jam <em>off-peak</em> dan bekukan rekrutmen baru.", "Reduce <em>part-time</em> employee shifts during <em>off-peak</em> hours and freeze new recruitment.")
c = c.replace("Pelayanan bisa melambat saat terjadi lonjakan pesanan mendadak.", "Service may slow down during sudden order surges.")
c = c.replace("Menjaga moral tim dan kualitas layanan tetap prima.", "Maintains team morale and top service quality.")
c = c.replace("Memerlukan biaya <em>marketing</em> tambahan yang membebani kas.", "Requires additional <em>marketing</em> costs that burden cash.")
c = c.replace("<strong>Perombakan SOP.</strong>", "<strong>SOP Revamp.</strong>")
c = c.replace("Kurangi ketergantungan pada pramusaji dengan sistem <em>Self-Service</em> atau <em>QR Ordering</em>.", "Reduce dependency on waiters with a <em>Self-Service</em> or <em>QR Ordering</em> system.")
c = c.replace("Butuh capex awal (investasi sistem) dan merubah <em>customer habit</em>.", "Needs initial capex (system investment) and changes <em>customer habit</em>.")
c = c.replace("Beban gaji ideal maksimal 30% dari omzet bruto. Memecat karyawan inti berisiko merusak layanan, sehingga pemotongan jam <em>part-time</em> atau efisiensi jam operasional lebih disarankan sebagai langkah pertama.", "Ideal salary burden is maximum 30% of gross revenue. Firing core employees risks damaging service, so cutting <em>part-time</em> hours or operational hour efficiency is recommended as a first step.")
c = c.replace("<strong>Audit Energi.</strong>", "<strong>Energy Audit.</strong>")
c = c.replace("Buat SOP jam nyala-mati AC/Lampu yang ketat. Evaluation tagihan listrik mingguan.", "Create strict AC/Lighting on-off SOPs. Evaluate weekly electricity bills.")
c = c.replace("<strong>Space Monetization.</strong>", "<strong>Space Monetization.</strong>")
c = c.replace("Sewakan area kosong ke <em>tenant</em> pelengkap atau manfaatkan dapur sebagai <em>Cloud Kitchen</em>.", "Rent empty areas to complementary <em>tenants</em> or utilize the kitchen as a <em>Cloud Kitchen</em>.")
c = c.replace("Memakan waktu untuk mencari <em>tenant</em> dan negosiasi.", "Takes time to find <em>tenants</em> and negotiate.")
c = c.replace("<strong>Accept Reality.</strong>", "<strong>Accept Reality.</strong>")
c = c.replace("Asumsikan ini adalah siklus <em>low-season</em> alami. Turunkan stock harian untuk menghindari <em>food waste</em>.", "Assume this is a natural <em>low-season</em> cycle. Lower daily stock to avoid <em>food waste</em>.")
c = c.replace("<strong>Standarisasi SOP.</strong>", "<strong>SOP Standardization.</strong>")
c = c.replace("Jadikan SOP dan Manajer location ini sebagai <em>benchmark</em> untuk direplikasi ke location lain.", "Make this location's SOP and Manager a <em>benchmark</em> to replicate to other locations.")
c = c.replace("Mengangkat performa location lain yang sedang *under-performing*.", "Boosts performance of other *under-performing* locations.")
c = c.replace("Dapat memecah fokus Manajer Bintang dari location utamanya.", "May divide the Star Manager's focus from their main location.")
c = c.replace("<strong>Bonus Pegawai.</strong>", "<strong>Employee Bonus.</strong>")
c = c.replace("Pertimbangkan memberikan insentif performa bagi staf di location ini untuk menjaga retensi.", "Consider giving performance incentives for staff in this location to maintain retention.")
c = c.replace("Menambah beban pengeluaran kas ekstra di akhir bulan.", "Adds extra cash expense burden at the end of the month.")
c = c.replace("<strong>Tambah Kapasitas.</strong>", "<strong>Add Capacity.</strong>")
c = c.replace("Alihkan fokus ke ekspansi penjualan (tambah kapasitas kursi, jam operasional, pesan antar).", "Shift focus to sales expansion (add seating capacity, operational hours, delivery).")
c = c.replace("Mendobrak <em>ceiling revenue</em> dan meningkatkan utilitas aset harian.", "Break the <em>revenue ceiling</em> and increase daily asset utility.")
c = c.replace("Memerlukan injeksi modal (Capex) untuk renovasi/marketing.", "Requires capital injection (Capex) for renovation/marketing.")
c = c.replace("Rasio di bawah target. Verifikasi konsistensi standar porsi.", "Ratio below target. Verify portion standard consistency.")
c = c.replace("Rasio efisien. Pertahankan standar resep saat ini.", "Efficient ratio. Maintain current recipe standard.")
c = c.replace("Proporsi di atas standar. Analysis potensi inefisiensi pengadaan.", "Proportion above standard. Analyze procurement inefficiency potential.")
c = c.replace("Rasio di bawah target. Pantau potensi kelelahan staf.", "Ratio below target. Monitor potential staff fatigue.")
c = c.replace("Pengeluaran staf efisien. Pertahankan produktivitas.", "Staff spending efficient. Maintain productivity.")
c = c.replace("Proporsi meningkat. Tinjau jam lembur dan jadwal staf.", "Proportion increasing. Review overtime hours and staff schedules.")
c = c.replace("Indikasi inefisiensi. Evaluation struktur tim dan shift.", "Inefficiency indication. Evaluate team structure and shifts.")
c = c.replace("Rasio meningkat. Periksa tagihan listrik atau utilitas.", "Ratio increasing. Check electricity or utility bills.")
c = c.replace("Beban operasional tinggi. Segera audit sewa dan utilitas bulanan.", "High operational burden. Audit monthly rent and utilities immediately.")
c = c.replace("Waktu layanan (serving time) melambat tajam, order error rate spikes, dan staf lama terancam <em>resign</em> karena kelelahan (burnout).", "Service time slows down sharply, order error rate spikes, and veteran staff are threatened to <em>resign</em> due to exhaustion (burnout).")
c = c.replace("📌 <strong>Risiko Ketergantungan:</strong> Jika porsi menu Top 5 mendominasi terlalu besar, pastikan ketersediaan bahan baku untuk menu tersebut tidak pernah putus, karena jika kosong, restoran kehilangan mayoritas omzetnya.", "📌 <strong>Dependency Risk:</strong> If the Top 5 menus dominate too much, ensure raw material availability never breaks, because if empty, the restaurant loses most of its revenue.")
c = c.replace("📌 <strong>Anomali Pergerakan:</strong> Perhatikan arah dan panjang batang pada grafik untuk melihat tren persentase. Lalu, cek tabel di sebelahnya untuk memvalidasi apakah persentase tersebut berdampak signifikan secara porsi riil.", "📌 <strong>Movement Anomaly:</strong> Pay attention to the direction and length of bars on the graph to see percentage trends. Then, check the adjacent table to validate if the percentage has a significant real portion impact.")
c = c.replace("📌 <strong>Analysis Kuartalan:</strong> Membantu mengidentifikasi faktor musiman (seasonality) dan stabilitas laba bersih per kuartal secara konsisten.", "📌 <strong>Quarterly Analysis:</strong> Helps identify seasonal factors (seasonality) and net profit stability per quarter consistently.")
c = c.replace("📌 <strong>Analysis YoY:</strong> Memberikan pandangan makro mengenai apakah location ini secara fundamental bertumbuh, stabil, atau mengalami perlambatan dari tahun ke tahun.", "📌 <strong>YoY Analysis:</strong> Provides a macro view on whether this location is fundamentally growing, stable, or slowing down year over year.")
c = c.replace("⚠️ Deep Dive Belum Tersedia", "⚠️ Deep Dive Not Available")
c = c.replace("Location ini belum punya data cukup untuk diagnosis detail", "This location does not have enough data for a detailed diagnosis")
c = c.replace("Pilih location lain atau cek apakah data revenue, net revenue, dan biaya untuk location ini sudah masuk lengkap pada horizon 30 sampai 90 hari.", "Select another location or check if revenue, net revenue, and cost data for this location are fully entered within the 30 to 90 day horizon.")
c = c.replace('title="Tahun"', 'title="Year"')
c = c.replace('title="Omzet (Gross)"', 'title="Gross Revenue"')
c = c.replace("Statistik Sejarah Location", "Location Historical Statistics")
c = c.replace("Tanggal Transaksi Pertama", "First Transaction Date")
c = c.replace("Rata-rata Margin Bersih Historis", "Historical Average Net Margin")

f.write_text(c)
