import glob
from pathlib import Path
import os

translations = {
    'Status Utama & Gap': 'Main Status & Gap',
    'Baca cepat volume order, AOV, dan gap ketimpangan antar location di seluruh outlet.': 'Quickly read order volume, AOV, and inequality gaps across all outlets.',
    'Baca analisis pertumbuhan jangka panjang, profitabilitas, dan strategi portofolio location.': 'Read long-term growth analysis, profitability, and location portfolio strategy.',
    'location sehat': 'healthy locations',
    'Setengah location mulai tertekan, perlu pengawasan aktif.': 'Half of locations are starting to be pressured, active supervision needed.',
    'Cabang Pusat': 'Downtown Branch',
    'Cabang Utara': 'Northside Branch',
    'Cabang Timur': 'Eastside Branch',
    'Cabang Selatan': 'Southside Branch',
    'Margin 30H dan 90H sama-sama lemah (< 5%). Perlu pembenahan struktural.': '30D and 90D margins are both weak (< 5%). Structural improvements needed.',
    'Anomali Demand Drop': 'Demand Drop Anomaly',
    'Omzet drop >10% bulan ini.': 'Revenue dropped >10% this month.',
    'Rata-rata omzet per struk.': 'Average revenue per receipt.',
    'Indikator Tahan Banting': 'Resilience Indicator',
    'Margin 30H dan 90H sama-sama sedang (5-10%). Bukan krisis, tapi belum optimal.': '30D and 90D margins are moderate (5-10%). Not a crisis, but not yet optimal.',
    'Margin 30H (≥ 10%) dan 90H (≥ 10%) sama-sama kuat. Jadikan benchmark operasional.': '30D and 90D margins are strong (≥ 10%). Use as operational benchmark.',
    'Pusat Kendali Branch Performance': 'Branch Performance Control Center',
    'Pilih location tertentu untuk menganalisis tren margin harian, breakdown pos biaya operasional, dan sebaran jenis pesanan secara mendalam.': 'Select a specific location to deeply analyze daily margin trends, operational cost breakdowns, and order type distribution.',
    'KESIMPULAN EKSEKUTIF: Performance Location Prima': 'EXECUTIVE SUMMARY: Prime Location Performance',
    'Location beroperasi dengan efisien, mencetak omzet': 'Location operates efficiently, recording revenue',
    'dari 2.997 transaksi dalam 30 hari terakhir.': 'from transactions in the last 30 days.',
    'Margin bersih terpantau sehat di level': 'Net margin monitored healthy at level',
    'namun volume bisnis sedang mengalami kontraksi': 'however business volume is experiencing contraction',
    'dari baseline. Verifikasi pada grafik Kuartalan di bawah apakah penurunan ini murni efek siklus musiman (low-season). Tetap waspadai tren pergerakan biaya bahan.': 'from baseline. Verify on the Quarterly chart below whether this decline is purely a seasonal effect (low-season). Remain vigilant of Ingredient Cost trends.',
    'Pusat Rekomendasi Taktis': 'Tactical Recommendation Center',
    'Tindakan korektif & panduan strategis': 'Corrective action & strategic guidance',
    'Gunakan rekomendasi sistem di bawah ini untuk mengambil tindakan atas tekanan biaya, inefisiensi operasional, serta strategi optimalisasi pertumbuhan location.': 'Use the system recommendations below to take action on cost pressures, operational inefficiencies, and location growth optimization strategies.',
    'Rekomendasi Pemangkasan': 'Cost Cutting Recommendations',
    'Opsi A: Audit & Kontrol': 'Option A: Audit & Control',
    'Sidak & Stock Opname.': 'Surprise Inspection & Stock Opname.',
    'Fokus mencari anomali over-portioning atau pencurian fisik pada menu terlaris': 'Focus on finding over-portioning anomalies or physical theft on best-selling menus',
    'Pro: Hentikan kebocoran instan tanpa modal.': 'Pro: Stop instant leakage without capital.',
    'Kontra: Menurunkan moral tim jika dilakukan terlalu represif.': 'Con: Lowers team morale if done too repressively.',
    'Opsi B: Rekayasa Harga': 'Option B: Price Engineering',
    'Naikkan Harga 5-10%.': 'Raise Prices 5-10%.',
    'Terapkan pada menu Paket Keluarga (4) untuk melebarkan ruang margin seketika.': 'Apply to Family Package (4) menu to instantly widen margin space.',
    'Pro: Dampak margin langsung terasa hari ini.': 'Pro: Margin impact is felt instantly today.',
    'Kontra: Berisiko menurunkan traffic pelanggan jika sensitivitas harga tinggi.': 'Con: Risks lowering customer traffic if price sensitivity is high.',
    'Opsi C: Cross-Selling Paksa': 'Option C: Forced Cross-Selling',
    'Bundle Minuman. Wajibkan kasir melakukan bundling makanan berat dengan minuman bermargin tinggi.': 'Drink Bundles. Require cashiers to bundle heavy meals with high-margin drinks.',
    'Pro: AOV (Average Order Value) naik tanpa membebani COGS.': 'Pro: AOV rises without burdening COGS.',
    'Kontra: Memerlukan training kasir dan insentif penjualan.': 'Con: Requires cashier training and sales incentives.',
    'Biaya bahan baku (COGS) yang sehat maksimal berada di angka 30%.': 'Healthy raw Ingredient Costs (COGS) are a maximum of 30%.',
    'Jika menembus angka ini, biasanya disebabkan oleh limbah (food waste), harga supplier naik, atau porsi berlebihan.': 'If it exceeds this number, it is usually caused by food waste, rising supplier prices, or excessive portions.',
    'Landasan Teori:': 'Theoretical Basis:',
    'Operasional & Diagnostik': 'Operations & Diagnostics',
    'Bedah performa & detail biaya': 'Dissect performance & cost details',
    'Gunakan instrumen di bawah ini untuk menganalisis detail pengeluaran, radar peringatan operasional harian, serta tren perkembangan margin.': 'Use the instruments below to analyze expenditure details, daily operational warning radar, and margin development trends.',
    'Parameter Analysis': 'Analysis Parameters',
    'Terakhir': 'Last',
    'Selisih / Perubahan': 'Difference / Change',
    'Rata-rata Omzet Daysan': 'Average Daily Revenue',
    'Rata-rata Order Daysan': 'Average Daily Orders',
    'Target normal maks': 'Normal max target',
    'Rasio mulai naik. Tinjau ulang pemakaian bahan baku harian.': 'Ratio starting to rise. Review daily raw material usage.',
    'Krisis': 'Crisis',
    'Rasio sangat rendah. Risiko operasional dan pelayanan turun.': 'Ratio is very low. Operational and service risks decrease.',
    'Pengeluaran rendah. Pastikan utilitas fasilitas tetap memadai.': 'Low expenditure. Ensure facility utilities remain adequate.',
    'Target normal 30% didasarkan pada kaidah keuangan': 'The normal 30% target is based on financial rules',
    'Bahaya Under-Budget (Efisiensi Semu)': 'Danger of Under-Budget (False Efficiency)',
    'Proporsi Rincian Pengeluaran Location': 'Location Expenditure Breakdown Proportion',
    'Sewa Bangunan': 'Building Rent',
    'Listrik': 'Electricity',
    'Air': 'Water',
    'Lainnya': 'Others',
    'Ruang Data Pendukung': 'Supporting Data Room',
    'Pusat Data Ekstra & Perspektif Strategis': 'Extra Data Center & Strategic Perspective',
    'Gunakan lensa tambahan di bawah ini untuk membedah komposisi mesin pendapatan serta melacak pola tren kesehatan bisnis dalam jangka panjang (Kuartalan & YoY).': 'Use the additional lenses below to dissect the revenue engine composition and track long-term business health trend patterns (Quarterly & YoY).',
    'Risiko Ketergantungan: Jika porsi menu Top 5 mendominasi terlalu besar, pastikan ketersediaan bahan baku untuk menu tersebut tidak pernah putus, karena jika kosong, restoran kehilangan mayoritas omzetnya.': 'Dependency Risk: If the portion of Top 5 menus dominates too much, ensure raw material availability for those menus never breaks, because if empty, the restaurant loses the majority of its revenue.',
    'Menu Stabil': 'Stable Menus',
    'Menu mana yang mengalami perubahan tren terbesar?': 'Which menus experienced the biggest trend changes?',
    'Menampilkan menu dengan lonjakan dan penurunan persentase penjualan terbesar bulan ini.': 'Showing menus with the biggest sales percentage surges and declines this month.',
    'Sebelum': 'Before',
    'Sekarang': 'Now',
    'Anomali Pergerakan: Perhatikan arah dan panjang batang pada grafik untuk melihat tren persentase. Lalu, cek tabel di sebelahnya untuk memvalidasi apakah persentase tersebut berdampak signifikan secara porsi riil.': 'Movement Anomaly: Pay attention to the direction and length of the bars on the graph to see percentage trends. Then, check the adjacent table to validate whether that percentage has a significant real portion impact.',
    'Insight Operasional & Rekomendasi': 'Operational Insights & Recommendations',
    'Observasi: Jaringan Parasit & Subsidi Silang': 'Observation: Parasite Network & Cross-Subsidies',
    'Bulan ini, 2 location utama menyumbang': 'This month, 2 main locations contributed',
    'omzet jaringan. Namun secara mengejutkan, mereka memikul hingga': 'network revenue. But surprisingly, they shoulder up to',
    'dari total Profit Bersih perusahaan di tengah rata-rata transaksi': 'of the company\'s total Net Profit amid average transactions of',
    'struk. Ketimpangan ini mengindikasikan adanya subsidi silang ekstrem, di mana location dominan terpaksa menutup kebocoran margin dari location-location terbawah dalam ekosistem.': 'per receipt. This inequality indicates extreme cross-subsidies, where dominant locations are forced to cover margin leaks from bottom locations in the ecosystem.',
    'Catatan: Persentase kontribusi laba yang melampaui 100% adalah indikator matematis bahwa terdapat location lain di dalam jaringan yang saat ini sedang beroperasi dalam kondisi minus/merugi.': 'Note: A profit contribution percentage exceeding 100% is a mathematical indicator that other locations in the network are currently operating at a loss.',
    'Kontribusi Omzet': 'Revenue Contribution',
    'Penopang Profit': 'Profit Supporter',
    'trends Menurun': 'Declining trends',
    'Disclaimer: Analysis ini dikalkulasi secara otomatis oleh AI berdasarkan perbandingan rasio portofolio omzet dan profitabilitas lintas location selama 30 hari terakhir. Gunakan sebagai petunjuk arah (compass), namun tetap selaraskan dengan strategi ekspansi perusahaan.': 'Disclaimer: This analysis is automatically calculated by AI based on a comparison of revenue portfolio and profitability ratios across locations over the past 30 days. Use as a directional guide (compass), but keep it aligned with the company\'s expansion strategy.',
    'DINAMIKA PORTOFOLIO CABANG': 'LOCATION PORTFOLIO DYNAMICS',
    'Membedah Risiko Konsentrasi, Ekspansi, & Subsidi Silang': 'Dissecting Concentration Risk, Expansion, & Cross-Subsidies',
    'Memahami bagaimana ketergantungan pada segelintir location utama dan jebakan ekspansi buta dapat meruntuhkan fondasi arus kas seluruh jaringan bisnis Anda.': 'Understand how reliance on a handful of prime locations and blind expansion traps can crumble the cash flow foundation of your entire business network.',
    'Bahaya Risk Concentration': 'Danger of Risk Concentration',
    'Bergantung mutlak pada 1-2 location menciptakan kerentanan ekstrem terhadap insiden lokal': 'Absolute reliance on 1-2 locations creates extreme vulnerability to local incidents',
    'Ilusi Pertumbuhan': 'Illusion of Growth',
    'Laporan omzet grup yang meroket menutupi fakta bahwa gerai satelit lainnya perlahan mati': 'Skyrocketing group revenue reports obscure the fact that other satellite outlets are slowly dying',
    'Dikte Pemilik Lahan': 'Landlord Dictation',
    'Mudah diperas landlord location utama karena arus kas tak bisa hidup tanpa titik lokasi tersebut': 'Easily squeezed by prime location landlords because cash flow cannot survive without those points',
    'Ketergantungan pendapatan perusahaan di atas 60% pada kurang dari 3 titik lokasi meningkatkan risiko kebangkrutan sistemik hingga 2x lipat.': 'Company revenue dependency above 60% on fewer than 3 locations doubles the systemic bankruptcy risk.',
    'Prinsip Kerentanan Portofolio Ritel': 'Retail Portfolio Vulnerability Principles',
    'Jebakan Ekspansi & Subsidi Silang': 'Expansion & Cross-Subsidy Trap',
    'Subsidi Silang Berdarah': 'Bleeding Cross-Subsidies',
    'Margin murni kerja keras location flagship habis dibakar untuk menambal kerugian location bawah': 'Pure margins from hard work at flagship locations are burned to patch losses at bottom locations',
    'Kanibalisasi Traffic': 'Traffic Cannibalization',
    'Buka location baru yang terlalu dekat hanya memecah pelanggan ke 2 kasir dengan 2x lipat biaya sewa': 'Opening new locations too close only splits customers to 2 cashiers with double the rent costs',
    'Raksasa Tak Efisien': 'Inefficient Giant',
    'Gerai megah punya omzet raksasa namun persentase marginnya sering kalah telak dari gerai ruko kecil': 'Grand outlets have giant revenues but their margin percentages often lose badly to small shop outlets',
    'Membuka gerai satelit dalam radius kanibalisasi yang salah dapat menggerus margin operasional keseluruhan grup bisnis sebesar 15%-25% pada tahun pertama.': 'Opening satellite outlets in the wrong cannibalization radius can erode the overall operational margin of the business group by 15%-25% in the first year.',
    'Aliran Subsidi Silang: Proporsi Omzet vs Penopang Profit': 'Cross-Subsidy Flow: Revenue Proportion vs Profit Supporter',
    'Porsi Omzet': 'Revenue Portion',
    'Profit Bersih': 'Net Profit',
    'Porsi Profit Bersih': 'Net Profit Portion',
    'Margin Murni': 'Pure Margin',
    'Pilih Location': 'Select Location',
    'Total volume struk': 'Total receipt volume'
}

files = glob.glob('/home/faqih/projects/restaurant-demo/evidence_en/pages/02-branch-performance/**/*.md', recursive=True)

for f in files:
    try:
        content = Path(f).read_text()
        new_content = content
        
        # Sort keys by length descending to avoid partial replacements
        for k in sorted(translations.keys(), key=len, reverse=True):
            new_content = new_content.replace(k, translations[k])
            
        if new_content != content:
            Path(f).write_text(new_content)
            print(f"Translated {f}")
    except Exception as e:
        print(f"Error processing {f}: {e}")
