from pathlib import Path

f = Path('/home/faqih/projects/restaurant-demo/evidence_en/pages/02-branch-performance/deepdive.md')
c = f.read_text()

# Executive Summary
c = c.replace("dari <strong>{activeScorecard.ord_30d?.toLocaleString('id-ID')} transaksi</strong> dalam 30 hari terakhir.", 
              "from <strong>{activeScorecard.ord_30d?.toLocaleString('id-ID')} transactions</strong> in the last 30 days.")
c = c.replace("Margin bersih sehat di level", "Net margin is healthy at level")
c = c.replace("selaras dengan momentum omzet harian yang tumbuh", "aligning with daily revenue momentum that grew")
c = c.replace("dari baseline.", "from baseline.")
c = c.replace("namun volume bisnis sedang mengalami kontraksi", "however business volume is experiencing contraction")
c = c.replace("Verifikasi pada grafik Kuartalan di bawah apakah penurunan ini murni efek siklus musiman (low-season).", "Verify on the Quarterly chart below whether this decline is purely a seasonal effect (low-season).")
c = c.replace("Tetap waspadai tren pergerakan", "Remain vigilant of movement trends for")
c = c.replace("Performance location membutuhkan perhatian.", "Location performance needs attention.")
c = c.replace("Meski tren omzet tumbuh", "Although revenue trend grew")
c = c.replace("dengan total", "with a total of")
c = c.replace("margin bersih tertahan di ambang batas minimum", "net margin is stuck at the minimum threshold of")
c = c.replace("Ekspansi volume belum optimal menjadi laba.", "Volume expansion is not yet optimally translating to profit.")
c = c.replace("Selain tren omzet yang terkoreksi", "Besides the revenue trend correcting by")
c = c.replace("menjadi", "to")
c = c.replace("margin bersih juga tertahan di ambang batas minimum", "net margin is also stuck at the minimum threshold of")
c = c.replace("Pastikan apakah pelemahan ini murni dampak siklus musiman atau inefisiensi operasional.", "Ensure whether this weakening is purely a seasonal effect or operational inefficiency.")
c = c.replace("Tekanan utama saat ini bersumber dari", "The main pressure currently stems from")
c = c.replace("yang mulai mendekati batas toleransi.", "which is approaching tolerance limits.")
c = c.replace("Location memerlukan evaluasi operasional segera.", "Location requires immediate operational evaluation.")
c = c.replace("Meski berhasil mencetak pertumbuhan omzet", "Despite successfully recording revenue growth of")
c = c.replace("margin bersih tergerus parah ke level", "net margin eroded severely to level")
c = c.replace("Lonjakan trafik gagal dikonversi menjadi laba, indikasi taktik promo/diskon terlalu dalam.", "Traffic surge failed to convert to profit, indicating promo/discount tactics were too deep.")
c = c.replace("Location berada dalam tekanan ganda. Omzet terkoreksi", "Location is under double pressure. Revenue corrected by")
c = c.replace("dan margin bersih anjlok ke level kritis", "and net margin plummeted to critical level")
c = c.replace("Bahkan jika ini periode low-season, penurunan trafik seharusnya tidak merusak margin hingga separah ini.", "Even if this is a low-season period, traffic decline should not damage margin this severely.")
c = c.replace("Akar masalah terindikasi pada", "Root cause is indicated to be")
c = c.replace("yang mengalami deviasi dari batas efisiensi 30%.", "which experienced deviation from the 30% efficiency limit.")

# Tactics
c = c.replace("Tindakan korektif & panduan strategis", "Corrective action & strategic guidance")
c = c.replace("Fokus mencari anomali <em>over-portioning</em> atau pencurian fisik pada menu terlaris", "Focus on finding <em>over-portioning</em> anomalies or physical theft on best-selling menu")
c = c.replace("Hentikan kebocoran instan tanpa modal.", "Stop instant leakage without capital.")
c = c.replace("Menurunkan moral tim jika dilakukan terlalu represif.", "Lowers team morale if done too repressively.")
c = c.replace("Terapkan pada menu", "Apply to menu")
c = c.replace("untuk melebarkan ruang margin seketika.", "to instantly widen margin space.")
c = c.replace("Dampak margin langsung terasa hari ini.", "Margin impact is felt instantly today.")
c = c.replace("Berisiko menurunkan traffic pelanggan jika sensitivitas harga tinggi.", "Risks lowering customer traffic if price sensitivity is high.")
c = c.replace("Wajibkan kasir melakukan bundling makanan berat dengan minuman bermargin tinggi.", "Require cashiers to bundle heavy meals with high-margin drinks.")
c = c.replace("naik tanpa membebani COGS.", "rises without burdening COGS.")
c = c.replace("Memerlukan training kasir dan insentif penjualan.", "Requires cashier training and sales incentives.")
c = c.replace("Healthy raw Ingredient Costs (COGS) are a maximum of 30%. If it exceeds this number, it is usually caused by food waste, rising supplier prices, or excessive portions.", "Healthy raw Ingredient Costs (COGS) are a maximum of 30%. If it exceeds this number, it is usually caused by food waste, rising supplier prices, or excessive portions.")
c = c.replace("Rasio F&B 30-30-30-10", "F&B Ratio 30-30-30-10")

# Diagnostics
c = c.replace("Operasional & Diagnostik", "Operations & Diagnostics")
c = c.replace("Bedah performa & detail biaya", "Dissect performance & cost details")
c = c.replace("30 Days Terakhir", "Last 30 Days")
c = c.replace("90 Days Terakhir", "Last 90 Days")
c = c.replace("order", "orders")
c = c.replace("30% Bahan, 30% SDM, 30% Operasional, 10% Net Profit", "30% Material, 30% HR, 30% Operational, 10% Net Profit")
c = c.replace("Bedah sumber pembengkakan biaya (Bahan, SDM, Operasional) untuk mengetahui pos pengeluaran mana yang butuh efisiensi segera.", "Dissect sources of cost swelling (Material, HR, Operational) to determine which expenditure items need immediate efficiency.")
c = c.replace("Lainnya (Marketing, dsb)", "Others (Marketing, etc)")

c = c.replace("Risiko Ketergantungan: Jika porsi menu Top 5 mendominasi terlalu besar, pastikan ketersediaan bahan baku untuk menu tersebut tidak pernah putus, karena jika kosong, restoran kehilangan mayoritas omzetnya.", "Dependency Risk: If the portion of Top 5 menus dominates too much, ensure raw material availability for those menus never breaks, because if empty, the restaurant loses the majority of its revenue.")
c = c.replace("Anomali Pergerakan: Perhatikan arah dan panjang batang pada grafik untuk melihat tren persentase. Lalu, cek tabel di sebelahnya untuk memvalidasi apakah persentase tersebut berdampak signifikan secara porsi riil.", "Movement Anomaly: Pay attention to the direction and length of the bars on the graph to see percentage trends. Then, check the adjacent table to validate whether that percentage has a significant real portion impact.")

f.write_text(c)
print("Updated deepdive.md")
