name: 'dbt_restaurant_en'
version: '1.0.0'

profile: 'dbt_restaurant_en'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_restaurant_en:
    staging:
      +materialized: view
      +schema: staging
    foundation:
      +materialized: table
      +schema: foundation
    marts:
      +materialized: table
      +schema: marts
