import os

replacements = {
    "Dua metrik di bawah ini dirancang untuk menjawab: apakah ada pola musiman yang perlu diantisipasi, dan apakah bisnis membaik secara fundamental dari tahun ke tahun?": "The two metrics below are designed to answer: are there seasonal patterns to anticipate, and is the business fundamentally improving year over year?",
    "Secara fundamental, bisnis mencatatkan pergerakan margin yang": "Fundamentally, the business recorded margin movements that",
    "Namun, yang paling krusial untuk ditindaklanjuti adalah momentum 90 Hari Terakhir:": "However, the most crucial to follow up is the Last 90 Days momentum:",
    "dibandingkan 90 hari sebelumnya. Tabel di bawah membedah location mana yang paling memicu pergerakan tersebut.": "compared to the previous 90 days. The table below dissects which location triggered the movement the most.",
    "Catatan Data Berjalan:": "Running Data Note:",
    "Baris teratas yang disorot menampilkan data kuartal yang belum selesai": "The highlighted top row displays quarterly data that is unfinished",
    "Baris teratas yang disorot menampilkan data tahun berjalan yang belum selesai": "The highlighted top row displays current year data that is unfinished",
    "Fluktuasi pada periode ini wajar terjadi sebelum tutup buku di akhir kuartal.": "Fluctuations in this period are normal before closing the books at the end of the quarter.",
    "Fluktuasi pada periode ini wajar terjadi sebelum tutup buku di akhir tahun.": "Fluctuations in this period are normal before closing the books at the end of the year.",
    "Membandingkan margin": "Comparing margin",
    "(sejak 1 Januari hingga data terbaru) melawan periode yang persis sama tahun lalu": "(from January 1 to the latest data) against the exact same period last year",
    "margin kita saat ini": "our current margin is",
    "Jika metrik di atas mengevaluasi kesehatan restoran secara keseluruhan (Makro), tabel di bawah membedah masalah tersebut ke masing-masing location (Mikro).": "If the metrics above evaluate the overall restaurant health (Macro), the table below dissects the problem into each location (Micro).",
    "Angka Rupiah yang muncul adalah target finansial yang bisa Anda selamatkan atau pakai untuk alokasi": "The Rupiah figure that appears is the financial target you can save or use for allocation",
    "Angka Rupiah yang muncul adalah target finansial yang bisa Anda selamatkan dari beban": "The Rupiah figure that appears is the financial target you can save from expenses",
    "Angka Rupiah yang muncul adalah target finansial yang bisa Anda selamatkan atau pakai untuk evaluasi": "The Rupiah figure that appears is the financial target you can save or use for evaluating",
    "Bedah sumber pembengkakan utilitas atau biaya overhead lainnya untuk mengetahui pos pengeluaran mana yang butuh efisiensi segera.": "Dissect the source of utility swelling or other overhead costs to find out which expense items need immediate efficiency.",
    "Bedah sumber pembengkakan biaya (Bahan, SDM, Operasional) untuk mengetahui pos pengeluaran mana yang butuh efisiensi segera.": "Dissect the source of cost swelling (Ingredients, HR, Operations) to find out which expense items need immediate efficiency.",
    "Menampilkan daftar detail bahan baku yang menyentuh batas Warning/Critical berdasarkan kategorinya.": "Displays a detailed list of raw materials that touch the Warning/Critical limits based on their categories.",
    "Tidak ada indikasi lonjakan harga bahan baku yang merugikan.": "There is no indication of detrimental raw material price spikes.",
    "Beras, minyak, dan gas adalah barang pabrikan. Jika harga merangkak naik, ini menandakan inflasi riil yang akan bertahan lama.": "Rice, oil, and gas are manufactured goods. If prices creep up, this indicates real inflation that will last a long time.",
    "Visualisasi proporsi uang belanja yang dialokasikan ke masing-masing supplier. Ketergantungan ekstrem (>50% ke satu supplier) berisiko mematikan operasional jika supplier tersebut bermasalah.": "Visualization of the proportion of shopping money allocated to each supplier. Extreme dependency (>50% to one supplier) risks killing operations if the supplier has problems.",
    "Status kinerja ditentukan dari kombinasi tiga metrik utama: Ketepatan Waktu pengiriman (On-Time), Keutuhan Pesanan (In-Full), dan tingkat barang yang ditolak/rusak (Defect Rate).": "Performance status is determined from a combination of three main metrics: On-Time delivery, In-Full orders, and Defect Rate.",
    "Menyoroti supplier yang menunjukkan kinerja buruk dalam 2 bulan terakhir.": "Highlights suppliers showing poor performance in the last 2 months.",
    "Nilai uang yang dikeluarkan untuk pengadaan bahan dalam 30H terakhir.": "The value of money spent on material procurement in the last 30 Days.",
    "Buat SOP jam nyala-mati AC/Lampu yang ketat. Evaluation tagihan listrik mingguan.": "Create strict AC/Light on-off SOPs. Evaluate weekly electricity bills.",
    "Overhead melebihi 30% adalah silent killer karena bersifat fixed-cost (harus dibayar meski restoran tidak ada pembeli). Bernegosiasi ulang biaya sewa saat bisnis tertekan adalah praktik korporat yang wajar.": "Overhead exceeding 30% is a silent killer because it is a fixed-cost (must be paid even if the restaurant has no buyers). Renegotiating rental costs when business is pressured is a reasonable corporate practice.",
    "Mengangkat performa location lain yang sedang *under-performing*.": "Lifting the performance of other locations that are *under-performing*.",
    "Menu mana yang mengalami perubahan tren terbesar?": "Which menu experienced the biggest trend change?",
    "Menampilkan menu dengan lonjakan dan penurunan persentase penjualan terbesar bulan ini.": "Displays menus with the biggest sales percentage spikes and drops this month.",
    "Catatan: Persentase kontribusi laba yang melampaui 100% adalah indikator matematis bahwa terdapat location lain di dalam jaringan yang saat ini sedang beroperasi dalam kondisi minus/merugi.": "Note: A profit contribution percentage exceeding 100% is a mathematical indicator that there are other locations in the network currently operating at a loss.",
    "Meskipun": "Although",
    "location utama": "main locations",
    "berhasil mendominasi": "managed to dominate",
    "dari total omzet, kontribusi laba bersihnya justru tertinggal secara proporsional di angka": "of total revenue, its net profit contribution lagged proportionally at",
    "Rata-rata transaksi jaringan berjalan stabil di angka Rp": "The average network transaction runs stably at Rp",
    "Fenomena ini mengindikasikan bahwa tingginya volume penjualan di location raksasa dibarengi dengan inefisiensi beban operasional yang menggerus profitabilitasnya.": "This phenomenon indicates that the high sales volume in giant locations is accompanied by operational inefficiencies that erode profitability.",
    "Porsi omzet dan laba berjalan lurus:": "Revenue and profit portions run parallel:",
    "menopang": "support",
    "omzet sekaligus": "revenue and",
    "laba bersih jaringan.": "network net profit.",
    "Tingkat ketergantungan absolut ini memicu \"Pemusatan Risiko\"": "This absolute dependency level triggers \"Risk Concentration\"",
    "yang sangat pekat, sehingga stabilitas kas perusahaan bertumpu sepenuhnya pada urat nadi segelintir lokasi tersebut.": "which is very dense, so the company cash stability relies completely on the lifeblood of these few locations.",
    "Standardisasi operasional terbukti prima. Sumbangan": "Operational standardization is proven prime. Contribution",
    "berbanding lurus dengan porsi laba bersihnya yang tersebar sehat di kisaran": "is directly proportional to its net profit portion distributed healthily around",
    "Keseimbangan rasio ini membuktikan ketiadaan monopoli risiko tunggal, menandakan ekosistem portofolio yang tangguh dan terdesentralisasi dengan baik.": "This ratio balance proves the absence of a single risk monopoly, indicating a resilient and well-decentralized portfolio ecosystem.",
    "Laporan omzet grup yang meroket menutupi fakta bahwa gerai satelit lainnya perlahan mati": "Skyrocketing group revenue reports cover up the fact that other satellite outlets are slowly dying",
    "Buka location baru yang terlalu dekat hanya memecah pelanggan ke 2 kasir dengan 2x lipat biaya sewa": "Opening new locations too close only splits customers into 2 registers with 2x the rent cost",
    "Membuka gerai satelit dalam radius kanibalisasi yang salah dapat menggerus margin operasional keseluruhan grup bisnis sebesar": "Opening satellite outlets in the wrong cannibalization radius can erode the entire business group operational margin by",
    "pada tahun pertama.": "in the first year.",
    "Margin Tinggi + Pengunjung Naik:": "High Margin + Rising Visitors:",
    "Location andalan yang berkontribusi positif pada profitabilitas dan pangsa pasar.": "Flagship locations contributing positively to profitability and market share.",
    "Margin Tinggi + Pengunjung Turun:": "High Margin + Falling Visitors:",
    "Location yang masih memberikan margin positif namun secara perlahan mulai mengalami penyusutan pelanggan.": "Locations still providing positive margins but slowly starting to experience customer shrinkage.",
    "Margin Minus + Pengunjung Turun:": "Minus Margin + Falling Visitors:",
    "Location dengan kondisi operasional defisit yang siklus operasinya disokong murni dari subsidi silang.": "Locations with deficit operational conditions whose operational cycles are purely supported by cross-subsidies.",
    "Catatan:": "Note:",
    "Metrik Margin dan Order menggunakan perhitungan": "Margin and Order metrics use",
    "Angka pertumbuhan (▲/▼) membandingkan kinerja kalender berjalan tahun ini dengan hari yang sama pada tahun sebelumnya, sehingga terbebas dari bias musiman.": "Growth figures (▲/▼) compare current year calendar performance with the same day last year, thus free from seasonal bias.",
    "Margin 30H menunjukkan kondisi aktif yang perlu diputuskan sekarang.": "30D Margin shows the active condition that needs to be decided now.",
    "Akhir pekan mendominasi telak. Maksimalkan stock Jumat-Minggu, tekan biaya operasional hari kerja.": "Weekends heavily dominate. Maximize Fri-Sun stock, press workday operational costs.",
    "Lebih ramai di akhir pekan. Geser jadwal libur staf inti ke awal minggu (Senin/Selasa).": "Busier on weekends. Shift core staff days off to early week (Mon/Tue).",
    "Volume pesanan sangat konsisten tiap hari. Terapkan jadwal shift dan stock yang merata.": "Order volume very consistent every day. Apply even shift and stock schedules.",
    "Ditopang pekerja kantoran. Jam makan siang krusial, siapkan promo keluarga di akhir pekan.": "Supported by office workers. Lunch hour is crucial, prepare family promos on weekends.",
    "Sangat bergantung jam kantor. Tekan drastis jumlah staf saat akhir pekan untuk efisiensi.": "Highly dependent on office hours. Drastically cut staff count on weekends for efficiency.",
    "Persentase total transaksi harian yang terjadi di jam-jam puncak.": "Percentage of total daily transactions occurring during peak hours.",
    "Panduan Membaca": "Reading Guide",
    "Semua Hari": "All Days",
    "Area hijau (Takeaway) dan oranye (Delivery) yang membesar menandakan pergeseran perilaku pelanggan. Data ini bisa digunakan untuk antisipasi stock kemasan (dus/plastik).": "Expanding green (Takeaway) and orange (Delivery) areas indicate customer behavior shifts. This data can be used to anticipate packaging stock (boxes/plastics).",
    "Silakan pilih minimal satu location yang valid di kotak filter di atas.": "Please select at least one valid location in the filter box above.",
    "Siapa yang mendominasi pesanan di location ini?": "Who dominates orders at this location?",
    "Mendeteksi hari-hari dalam seminggu yang secara historis memiliki volume pesanan tertinggi.": "Detects days in a week that historically have the highest order volume.",
    "Untuk menjaga akurasi perbandingan, seluruh perhitungan kuartal dan grafik musiman di halaman ini hanya memproses bulan operasional yang sudah selesai penuh. Data bulan berjalan sengaja dikecualikan agar tidak memicu bias tren yang dapat merusak akurasi rekomendasi strategi.": "To maintain comparison accuracy, all quarterly calculations and seasonal charts on this page only process fully completed operational months. Current month data is intentionally excluded so as not to trigger trend bias that could ruin strategy recommendation accuracy.",
    "Melacak siklus tren jangka panjang (tahunan) untuk melihat apakah ada bulan atau kuartal tertentu yang secara konsisten selalu lebih ramai, sehingga Anda bisa merencanakan kapasitas staf dan stock jauh-jauh hari.": "Tracks long-term (yearly) trend cycles to see if certain months or quarters are consistently busier, so you can plan staff and stock capacity far in advance.",
    "Gap ekstrem, butuh penyesuaian kapasitas yang signifikan.": "Extreme gap, needs significant capacity adjustment.",
    "Analisis di bawah ini merangkum perbandingan langsung performa restoran saat musim liburan melawan hari-hari reguler, serta rekomendasi kapasitas yang dapat Anda ambil.": "The analysis below summarizes direct comparisons of restaurant performance during holiday seasons versus regular days, as well as capacity recommendations you can take.",
    "Selama musim tinggi (Peak Season) yang mencakup Libur Sekolah, Akhir Tahun, dan Periode Ramadan/Lebaran, restoran Anda mengalami perubahan traffic sebesar": "During peak season which includes School Holidays, Year End, and Ramadan/Eid Periods, your restaurant experiences a traffic change of",
    "dibandingkan hari-hari biasa. Gunakan angka ini sebagai patokan penambahan atau pengurangan staf temporer.": "compared to regular days. Use this figure as a benchmark for adding or reducing temporary staff.",
    "Pertahankan kapasitas staf yang konsisten.": "Maintain consistent staff capacity.",
    "Tidak ada pergeseran musiman signifikan — rotasi staf bisa dijadwalkan kapan saja tanpa mengganggu momen ramai.": "No significant seasonal shift — staff rotation can be scheduled anytime without disrupting busy moments.",
    "Rencanakan pengadaan berbasis rata-rata.": "Plan procurement based on average.",
    "Tidak ada lonjakan musiman yang memerlukan buffer stock ekstra secara rutin.": "No seasonal spikes requiring extra buffer stock routinely.",
    "Bulan ini, rata-rata rasio bahan pokok sangat tinggi": "This month, the average raw material ratio is very high",
    "Angka di atas 35% mengindikasikan pemborosan ekstrem atau pencurian/kerusakan stock yang menggerus profit bersih perusahaan. Kondisi terparah saat ini terjadi di": "Figures above 35% indicate extreme waste or stock theft/spoilage eroding the company's net profit. The worst condition currently occurs at",
    "Segera audit resep, timbangan porsi, dan laporan stock rusak (spoilage) di location-location yang merah.": "Immediately audit recipes, portion scales, and spoilage reports in red locations.",
    "Seluruh komponen pengeluaran dapur sangat terjaga": "All kitchen expense components are well-maintained",
    "sesuai target 30%. Perusahaan menikmati margin kotor yang optimal. Prestasi efisiensi terbaik dicapai oleh": "according to the 30% target. The company enjoys an optimal gross margin. The best efficiency achievement was reached by",
    "Rasio pengeluaran bahan sangat minim": "Material expense ratio is very minimal",
    "jauh di bawah standar rata-rata 30%. Secara laba sangat bagus, namun pastikan hal ini bukan akibat pengurangan kualitas porsi bahan yang bisa mengecewakan pelanggan. Angka terendah dicatat": "far below the 30% average standard. In terms of profit it is very good, but ensure this is not due to reducing material portion quality which could disappoint customers. The lowest figure was recorded by",
    "Pastikan SOP penyajian dipatuhi dan tidak ada bahan (daging/sayur) yang dipotong porsinya demi menghemat.": "Ensure serving SOPs are adhered to and no ingredients (meat/vegetables) are portion-cut to save money.",
    "Tabel di bawah menyoroti location mana yang mengalami pemborosan bahan mentah dibandingkan dengan target ideal 30% dari omzet.": "The table below highlights which locations experienced raw material waste compared to the ideal target of 30% of revenue.",
    "Pertimbangkan untuk menyetop lembur yang tidak perlu.": "Consider stopping unnecessary overtime.",
    "Rata-rata rasio gaji turun drastis menyentuh batas kritis di bawah 15%. Ini pertanda restoran sangat kekurangan staf, yang bisa memicu karyawan kelelahan ekstrim dan keluhan pelanggan. Hal ini paling parah di": "The average salary ratio dropped drastically touching the critical limit below 15%. This is a sign the restaurant is severely understaffed, which can trigger extreme employee burnout and customer complaints. This is worst at",
    "Pertahankan jadwal kerja yang ada saat ini.": "Maintain current work schedules.",
    "(Catatan: Terus pantau kenyamanan kerja karyawan di lapangan).": "(Note: Continue monitoring employee work comfort in the field).",
    "Dari setiap Rp100 gross revenue 30 hari terakhir, berapa yang habis untuk bahan, SDM, dan operasional.": "For every Rp100 gross revenue in the last 30 days, how much was spent on materials, HR, and operations.",
    "1. Pilih Umpan Trafik (Lihat Tabel Kanan):": "1. Select Traffic Bait (See Right Table):",
    "Pilih satu menu dari daftar \"Pekerja Keras\". Pastikan ini adalah menu utama yang populer. (Contoh:": "Select one menu from the \"Workhorse\" list. Ensure this is a popular main menu. (Example:",
    "2. Pilih Pendongkrak Margin (Lihat Tabel Kiri):": "2. Select Margin Booster (See Left Table):",
    "Pilih satu menu dari daftar \"Harta Karun\" yang cocok mendampingi menu pertama. (Contoh:": "Select one menu from the \"Treasure\" list suitable for accompanying the first menu. (Example:",
    "Semua menu yang penjualannya meroket, konsisten, atau sekadar turun tipis (<20%) dianggap sehat secara tren dan dihitung sebagai Stable Menus.": "All menus whose sales skyrocketed, were consistent, or just slightly dropped (<20%) are considered healthy in trend and counted as Stable Menus.",
    "Mengambil data riwayat harga dari bahan baku yang saat ini menyentuh": "Retrieves price history data of raw materials currently touching",
    "Tabel ini menyoroti supplier yang mendapatkan status Evaluation (C)": "This table highlights suppliers receiving Evaluation (C) status",
    "Dapur terpaksa membeli bahan dadakan dari pasar lokal dengan harga retail (non-grosir) yang jauh lebih merugikan.": "The kitchen was forced to buy impromptu materials from local markets at much more detrimental retail (non-wholesale) prices.",
    "Pelanggan restoran reguler yang mendapati menu favoritnya sold-out memiliki 30% probabilitas untuk tidak pernah kembali lagi ke gerai Anda.": "Regular restaurant customers who find their favorite menu sold-out have a 30% probability of never returning to your outlet again.",
    "Menampilkan histori pergerakan harga harian untuk item yang menyentuh batas Warning/Critical berdasarkan kategorinya.": "Displays historical daily price movements for items touching Warning/Critical limits based on categories.",
    "Ada item yang mendekati habis. Prioritas pertama adalah mencegah menu tidak bisa dijual.": "There are items close to running out. The first priority is to prevent menus from being unsellable.",
    "Mencari bahan baku yang kritis di satu location (stock < 3 hari)": "Looking for critical raw materials at one location (stock < 3 days)",
    "Margin bersih sehat di level": "Healthy net margin at level",
    "selaras dengan momentum omzet harian yang tumbuh": "in line with daily revenue momentum growing",
    "dari baseline.": "from baseline.",
    "Selain tren omzet yang terkoreksi": "In addition to the revenue trend corrected by",
    "menjadi": "to",
    "margin bersih juga tertahan di ambang batas minimum": "net margin is also held at the minimum threshold of",
    "Pastikan apakah pelemahan ini murni dampak siklus musiman atau inefisiensi operasional.": "Ensure whether this weakening is purely a seasonal cycle impact or operational inefficiency.",
    "Tekanan utama saat ini bersumber dari": "The main pressure currently stems from",
    "yang mulai mendekati batas toleransi.": "which is starting to approach tolerance limits.",
    "Akar masalah terindikasi pada": "The root cause is indicated at",
    "yang mengalami deviasi dari batas efisiensi 30%.": "which deviates from the 30% efficiency limit.",
    "Biaya bahan baku (COGS) yang sehat maksimal berada di angka 30%. Jika menembus angka ini, biasanya disebabkan oleh limbah (food waste), harga supplier naik, atau porsi berlebihan.": "A healthy raw material cost (COGS) is at a maximum of 30%. If it breaks this figure, it is usually caused by food waste, supplier prices rising, or excessive portions.",
    "Kontra: Memerlukan biaya marketing tambahan yang membebani kas.": "Cons: Requires additional marketing costs that burden cash.",
    "Pro: Mengangkat performa location lain yang sedang *under-performing*.": "Pros: Lifting the performance of other locations that are *under-performing*.",
}

import os
pages_dir = "pages/en"
for root, dirs, files in os.walk(pages_dir):
    for file in files:
        if file.endswith(".md"):
            filepath = os.path.join(root, file)
            with open(filepath, "r") as f:
                content = f.read()
            original_content = content
            for indo, eng in replacements.items():
                content = content.replace(indo, eng)
            if content != original_content:
                with open(filepath, "w") as f:
                    f.write(content)
                print(f"Patched {filepath}")
