import re

file_path = '/home/faqih/projects/restaurant-demo/evidence/pages/en/04-peak-hours/deepdive.md'
with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    # SQL day of week
    "'Minggu'": "'Sunday'",
    "'Senin'": "'Monday'",
    "'Selasa'": "'Tuesday'",
    "'Rabu'": "'Wednesday'",
    "'Kamis'": "'Thursday'",
    "'Jumat'": "'Friday'",
    "'Sabtu'": "'Saturday'",

    # SQL Weekend
    "'Weekend (Jum-Min)'": "'Weekend (Fri-Sun)'",
    "'Weekday (Sen-Kam)'": "'Weekday (Mon-Thu)'",

    # SQL Day Part
    "'Pagi (08-10)'": "'Morning (08-10)'",
    "'Makan Siang (11-13)'": "'Lunch (11-13)'",
    "'Sore (14-16)'": "'Afternoon (14-16)'",
    "'Makan Malam (17-20)'": "'Dinner (17-20)'",
    "'Larut Malam (21-22)'": "'Late Night (21-22)'",
    "'Pagi'": "'Morning'",
    "'Makan Siang'": "'Lunch'",
    "'Sore'": "'Afternoon'",
    "'Makan Malam'": "'Dinner'",
    "'Larut Malam'": "'Late Night'",

    # SQL Strength
    "'kuat'": "'strong'",
    "'moderat'": "'moderate'",
    "'lemah'": "'weak'",

    # SQL Months
    "'Mei'": "'May'",
    "'Agu'": "'Aug'",
    "'Okt'": "'Oct'",
    "'Des'": "'Dec'",

    # Labels and Titles
    "Jam Sibuk": "Peak Hours",
    "Hari Ramai": "Busy Days",
    "Pilih Location": "Select Location",
    "Pusat Kendali Jam & Hari Sibuk": "Peak Hours & Busy Days Control Center",
    "Pilih location tertentu untuk memfokuskan analisis kepadatan traffic, jam sibuk harian, dan tren akhir pekan.": "Select a specific location to focus traffic density analysis on daily peak hours and weekend trends.",
    "Akhir Pekan Ekstrem": "Extreme Weekend",
    "Cenderung Akhir Pekan": "Weekend Leaning",
    "Merata Stabil": "Evenly Stable",
    "Cenderung Hari Kerja": "Weekday Leaning",
    "Hari Kerja Ekstrem": "Extreme Weekday",
    "Distribusi Demand Harian": "Daily Demand Distribution",
    "Peta Kurva Nadi Operasional": "Operational Pulse Curve Map",
    "Bentuk kurva demand dari buka hingga tutup. Analisis pergeseran pola jam sibuk antara awal minggu hingga akhir pekan.": "Demand curve shape from open to close. Analysis of peak hour pattern shifts between early week and weekend.",
    "Konsentrasi Jam Sibuk": "Peak Hour Concentration",
    "Lonjakan Kesibukan": "Busyness Surge",
    "x Lipat": "x",
    "Perbandingan volume transaksi saat jam sibuk melawan rata-rata harian.": "Comparison of transaction volume during peak hours vs daily average.",
    "Zona Waktu Critical": "Critical Time Zone",
    "Periode krusial di mana staf dan bahan baku harus siap kapasitas 100%.": "Crucial period where staff and raw materials must be ready at 100% capacity.",
    "Perbandingan Jam Sibuk Antar Hari": "Peak Hour Comparison Between Days",
    "KURVA NADI DEMAND": "DEMAND PULSE CURVE",
    "Bagaimana bentuk lonjakan pesanan di setiap hari pada jam operasional?": "What is the shape of order surges each day during operational hours?",
    "Perbandingan kurva lonjakan jam kerja (08:00–22:00). Garis Biru Putus-putus (Senin–Kamis) mewakili hari kerja, sedangkan Garis Oranye/Amber Tebal (Jumat–Minggu) mewakili akhir pekan.": "Comparison of working hour surge curves (08:00-22:00). Dashed Blue Line (Mon-Thu) represents weekdays, while Thick Orange/Amber Line (Fri-Sun) represents weekends.",
    "Komposisi Tipe Pesanan": "Order Type Composition",
    "KOMPOSISI TIPE PESANAN PER JAM": "ORDER TYPE COMPOSITION PER HOUR",
    "Bagaimana pergeseran proporsi Dine-In vs Takeaway vs Delivery di setiap jam?": "How does the proportion of Dine-In vs Takeaway vs Delivery shift each hour?",
    "Pilih hari tertentu untuk membedah rincian persentase tipe pesanan (08:00–22:00). Gunakan data ini untuk mengantisipasi kebutuhan piring/meja vs kantong pembungkus.": "Select a specific day to dissect the order type percentage breakdown (08:00-22:00). Use this data to anticipate the need for plates/tables vs packaging bags.",
    "Rata-rata All Days": "All Days Average",
    "Hari Sibuk": "Busy Days",
    "Analisis Volume Hari Sibuk": "Busy Day Volume Analysis",
    "Gunakan instrumen di bawah ini untuk menganalisis beban operasional harian dan mengekstrak profil karakteristik mingguan.": "Use the instruments below to analyze daily operational load and extract weekly characteristic profiles.",
    "Karakteristik Demografi": "Demographic Characteristics",
    "Memecah proporsi pengunjung berdasarkan rasio aktivitas hari kerja vs akhir pekan.": "Breaking down visitor proportion based on weekday vs weekend activity ratio.",
    "Panduan Aksi (Profil Location):": "Action Guide (Location Profile):",
    "Gunakan rasio karakteristik location ini sebagai acuan utama (<i>baseline</i>) untuk merancang strategi <i>marketing</i> spesifik (kapan menebar promo diskon) dan menentukan kebijakan dasar alokasi hari libur mingguan bagi staf inti Anda.": "Use this location characteristic ratio as the main baseline to design specific marketing strategies (when to spread discount promos) and determine the basic policy for weekly days off for your core staff.",
    "Agregasi Volume Harian (30 Hari)": "Daily Volume Aggregation (30 Days)",
    "Kapan beban dapur mencapai titik puncaknya?": "When does the kitchen load reach its peak?",
    "Hari dalam Seminggu": "Day of the Week",
    "Total Order (30 Hari)": "Total Order (30 Days)",
    "Panduan Aksi (Makro):": "Action Guide (Macro):",
    "Jadwalkan <i>Prep-Day</i> (persiapan bahan baku masif) satu hari sebelum batang grafik memuncak. Gunakan hari-hari paling lesu untuk meluncurkan diskon <i>Flash Sale</i> guna meratakan beban dapur mingguan.": "Schedule Prep-Day (massive raw material preparation) one day before the graph bars peak. Use the most sluggish days to launch Flash Sale discounts to even out the weekly kitchen load.",
    "Trends Musiman": "Seasonal Trends",
    "Data Bulan Berjalan Dikecualikan": "Current Month Data Excluded",
    "Cara Membaca Musiman": "How to Read Seasonality",
    "Pembagian Kuartal": "Quarter Division",
    "Januari-Maret": "January-March",
    "Awal tahun; sering dipengaruhi efek setelah libur akhir tahun.": "Early year; often influenced by post-year-end holiday effects.",
    "April-Juni": "April-June",
    "Pertengahan pertama; bisa terpengaruh libur sekolah awal.": "First half; can be affected by early school holidays.",
    "Juli-September": "July-September",
    "Pertengahan kedua; sering membaca dampak libur sekolah dan normalisasi setelahnya.": "Second half; often reads the impact of school holidays and subsequent normalization.",
    "Oktober-Desember": "October-December",
    "Akhir tahun; biasanya menangkap periode libur akhir bulan Desember, dan budget akhir tahun.": "End of year; usually captures the late December holiday period, and year-end budgets.",
    "Metodologi Kalkulasi": "Calculation Methodology",
    "Gap Musiman": "Seasonal Gap",
    "Selisih kuartal kuat vs lemah": "Difference between strong vs weak quarters",
    "Gap besar berarti kapasitas tidak bisa dibuat rata sepanjang tahun. Gap kecil berarti demand stabil dan planning bisa memakai baseline umum.": "A large gap means capacity cannot be made even throughout the year. A small gap means stable demand and planning can use a general baseline.",
    "Efek Libur": "Holiday Effect",
    "Bulan liburan vs Bulan reguler": "Holiday month vs Regular month",
    "Membaca apakah musim liburan sekolah & akhir tahun menaikkan demand secara nyata dibanding bulan biasa.": "Reading whether school holidays & year-end seasons significantly increase demand compared to regular months.",
    "Rata-rata bulanan per kuartal": "Monthly average per quarter",
    "Perbandingan kuartal memakai rata-rata order bulanan agar kuartal dengan data tidak lengkap tidak otomatis kalah.": "Quarterly comparison uses monthly order average so quarters with incomplete data do not automatically lose.",
    "Pergeseran Musiman": "Seasonal Shifts",
    "Pola Historis Seluruh Periode": "Historical Pattern of All Periods",
    "Analisis pola permintaan jangka panjang untuk mengidentifikasi pergeseran musiman dan efek liburan sepanjang tahun.": "Analysis of long-term demand patterns to identify seasonal shifts and holiday effects throughout the year.",
    "Kuartal Puncak": "Peak Quarter",
    "Kuartal dengan rata-rata order bulanan tertinggi. Kapasitas operasional (staf & stock) harus siap maksimal di periode ini.": "Quarter with the highest monthly order average. Operational capacity (staff & stock) must be at maximum readiness during this period.",
    "Selisih volume demand antara kuartal puncak (": "Difference in demand volume between peak quarter (",
    ") dan terendah (": ") and lowest (",
    "Gap moderat, siapkan shift fleksibel.": "Moderate gap, prepare flexible shifts.",
    "Demand relatif stabil sepanjang tahun.": "Demand relatively stable throughout the year.",
    "Efek Musim Liburan": "Holiday Season Effect",
    "Perbandingan rata-rata pesanan pada bulan libur sekolah & akhir tahun dibanding bulan reguler.": "Comparison of average orders in school holiday & year-end months vs regular months.",
    "Perspektif Musiman": "Seasonal Perspective",
    "Baca pola tahunan untuk perencanaan kapasitas": "Read annual patterns for capacity planning",
    "Musim Liburan": "Holiday Season",
    "Juli, Desember & Musim Ramadan/Lebaran": "July, December & Ramadan/Eid Season",
    "Rata-rata Order / Bulan": "Average Orders / Month",
    "Selisih Traffic": "Traffic Difference",
    "Bulan Reguler": "Regular Month",
    "Hari Operasional Standar": "Standard Operational Days",
    "Perencanaan Kapasitas · Baca Staf, Stock, dan Marketing": "Capacity Planning · Read Staff, Stock, and Marketing",
    "Kapasitas Staf": "Staff Capacity",
    "Mulai rekrutmen atau pelatihan staf 6–8 minggu sebelum": "Start staff recruitment or training 6-8 weeks before",
    "Dengan selisih musiman": "With a seasonal gap of",
    "kapasitas staf reguler tidak cukup di kuartal puncak. Rekrut staf paruh waktu atau intensifkan training sebelum musim ramai.": "regular staff capacity is not enough in the peak quarter. Recruit part-time staff or intensify training before the busy season.",
    "Review kebutuhan staf 4–6 minggu sebelum": "Review staff needs 4-6 weeks before",
    "membutuhkan antisipasi ringan. Identifikasi apakah kapasitas saat ini bisa dioptimasi dengan rotasi shift sebelum memutuskan rekrutmen tambahan.": "requires light anticipation. Identify whether current capacity can be optimized with shift rotation before deciding on additional recruitment.",
    "Logistik & Pengadaan": "Logistics & Procurement",
    "Sesuaikan timeline pengadaan liburan.": "Adjust holiday procurement timeline.",
    "Efek libur": "Holiday effect of",
    "di atas normal berarti kebutuhan bahan baku lebih tinggi. Koordinasikan dengan supplier minimal 3–4 minggu sebelumnya.": "above normal means higher raw material needs. Coordinate with suppliers at least 3-4 weeks in advance.",
    "Fokus Pemasaran": "Marketing Focus",
    "Alokasikan porsi promosi ekstra di": "Allocate extra promotion portion in",
    "Untuk menambal kelesuan": "To patch the sluggishness of",
    "organik di kuartal terlemah, berikan porsi": "organic in the weakest quarter, provide a more aggressive",
    "lebih agresif. Sebaliknya saat kuartal puncak": "portion. Conversely during peak quarter",
    "akuisisi dan fokus maksimalkan profit.": "acquisition budget and focus on maximizing profit.",
    "Distribusikan anggaran promosi merata.": "Distribute promotional budget evenly.",
    "Trends order sangat stabil sepanjang tahun. Manuver": "Order trends are very stable throughout the year.",
    "drastis tidak diperlukan, cukup fokuskan pada program retensi reguler.": "Drastic maneuvers are not needed, just focus on regular retention programs.",
    "Distribusi Kuartal Historis": "Historical Quarter Distribution",
    "Bagaimana tren kuartalan terbentuk dari tahun ke tahun?": "How do quarterly trends form year over year?",
    "Total Order per Kuartal — per Tahun": "Total Orders per Quarter — per Year",
    "Kuartal": "Quarter",
    "Rata-Rata Historis per Kuartal": "Historical Average per Quarter",
    "Overview murni rata-rata performa antar kuartal (menghaluskan efek anomali lonjakan di tahun tertentu).": "Pure overview of average performance between quarters (smoothing out the effects of surge anomalies in specific years).",
    "Rata-rata Order": "Average Orders",
    "Porsi Order": "Order Portion",
    "Rata-rata Revenue (Rp)": "Average Revenue (Rp)",
    "Porsi Revenue": "Revenue Portion",
    "Data Historis Belum Cukup": "Insufficient Historical Data",
    "Silakan Pilih Location": "Please Select Location",
    "Pilih salah satu location di Pusat Kendali Musiman untuk memulai analisis data historisnya.": "Select a location in the Seasonal Control Center to start analyzing its historical data.",
    "Silakan Pilih Location Terlebih Dahulu": "Please Select Location First",
    "Gunakan menu pilihan location di atas untuk memuat diagnosis pola traffic, jam sibuk harian, dan tren musiman secara spesifik.": "Use the location selection menu above to load diagnosis of traffic patterns, daily peak hours, and seasonal trends specifically.",
    "Informasi Penting: ": "Important Information: ",
    "Data Tidak Ditemukan": "Data Not Found",
    "Selisih volume demand antara kuartal puncak": "Difference in demand volume between peak quarter",
    "dan terendah": "and lowest",
    "Selisih": "Difference of",
    "hemat": "save",
    "organik di kuartal terlemah, berikan porsi": "organic in the weakest quarter, provide a more aggressive",
    "kritis": "critical",
    "waspada": "warning",
    "sehat": "healthy"
}

for indo, eng in replacements.items():
    content = content.replace(indo, eng)

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

